algoritmo "subtração"
// Função : Fazer subtração de 2 números
// Autor : Renata Porto Gransoti
// Data : 24/08/2022
// Seção de Declarações 
var
  valor1, valor2, resultado: real
inicio
// Seção de Comandos 
escreval("Qual o valor 1?")
leia(valor1)
escreval("Qual o valor 2?")
leia(valor2)
resultado <- valor1 - valor2
escreval("O resultado de", valor1, " -", valor2, " é:", resultado)
fimalgoritmo
